### ISSUE TITLE
"Cannot call set data for current field type"

### ISSUE THREAD

**Issue by sstere** [contentstack/ui-extensions-sdk#50]
I get this exception when trying to modify a File field from the context of another custom field extension.

https://github.com/contentstack/ui-extensions-sdk/blob/1a902b4ca9549ad57e91daafcdc777ac18a2c4fb/lib/field.js#L80

Why does this limitation exists? I have a scenario when I need to modify a File field from the context of another custom field extension. Can you remove this limitation?

Thx!

**Comment by Deepak-Kharah** [comment]
Hey @sstere, we'll check it out from our end. Thanks.
